### ISSUE TITLE
Documentation...

### ISSUE THREAD

**Issue by tabr0201** [odoo/docker#16] opened 2015-04-11 16:17 UTC
I am new, and ran the containers per your documentation, but when I try to visit 127.0.0.1:8069 it just hangs and times out. I've also tried "boot2docker ip" and got "192.168.59.103" so I've tried:
http://www.192.168.59.103:8069
http://www.192.168.59.103:8071
http://www.192.168.59.103:8080

It seems to be running but I can't seem to access it. Any ideas?

**Comment by md5** [comment] 2015-04-12 23:24
What is the exact `docker run` command you used. If you used the one in the docs, then it's going to be listening on 127.0.0.1 on the Boot2Docker VM, not on your local host. You'll want to use a port mapping like `-p 8069:8069` to expose port 8069 on all addresses of the B2D VM, which will allow you to access http://192.168.59.103:8069

**Comment by movcale** [comment] 2015-05-28 07:04
If you use boot2docker for Windows, you should do like this
boot2docker ssh -L 8069:localhost:8069
or login via Putty with port 8069 forwarding

Please see this as reference
http://stackoverflow.com/questions/25560543/boot2docker-on-windows-cant-access-exposed-port

**Comment by sle-odoo** [comment] 2015-07-23 16:19
I'm closing this issue as there is no feedback following @movcale documentation link.
If the issue is still happening, feel free to comment with a complete description of how to reproduce your issue and i'll reopen.

Regards

**Closed by sle-odoo** 2015-07-23 16:19 UTC
