### ISSUE TITLE
return self.models[model_name]

### ISSUE THREAD

**Issue by W360S** [odoo/docker#216] opened 2018-10-05 02:24 UTC
ERROR odoo werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 255, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1317, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1290, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1470, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 176, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2018-10-05 02:23:38,837 1 INFO odoo werkzeug: 172.17.0.1 - - [05/Oct/2018 02:23:38] "GET /favicon.ico HTTP/1.1" 500 - 2 0.003 0.008
2018-10-05 02:23:38,840 1 ERROR odoo werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 255, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1317, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1290, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1470, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 176, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -

**Comment by W360S** [comment] 2018-10-05 02:32
2018-10-05 02:29:39,241 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database odoo. 
2018-10-05 02:30:33,348 1 ERROR odoo odoo.sql_db: bad query: b"SELECT latest_version FROM ir_module_module WHERE name='base'"
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^

**Comment by fernandogbj** [comment] 2018-10-05 21:50
Exactly the same mistake happens to me, does anyone have the solution?

**Comment by BusinessVisionEnforced** [comment] 2018-10-06 13:38
Also having this problem here

**Comment by wilk** [comment] 2018-10-09 14:34
same problem pulling odoo:12 and executing docker-compose as suggested inside the docs

**Comment by wilk** [comment] 2018-10-09 14:43
Solved with: https://github.com/odoo/odoo/issues/27447#issuecomment-427840100

**Comment by d-fence** [comment] 2018-10-10 09:06
Duplicate of the solved odoo/odoo#27447

**Closed by d-fence** 2018-10-10 09:06 UTC

**Comment by daudakhtar** [comment] 2018-11-19 08:01
return self.models[model_name]
KeyError: u'crm.lead.report'
