### ISSUE TITLE
Database error when adding a new language

### ISSUE THREAD

**Issue by Danisan** [odoo/docker#223] opened 2018-10-20 14:20 UTC
Steps to reproduce:
1. Create a new database, with no demo data, in english and with no country selected.
2. Install crm
3. add a partner (it works)
4. Go to settings / languages
5. pick a new language to add

get this:
```
odoo12c | 2018-10-20 14:14:40,707 1 ERROR odoo12_test_us odoo.sql_db: bad query: b" INSERT INTO ir_translation(name, lang, res_id, src, type, value, module, state, comments)\n                           SELECT name, lang, res_id, src, type, value, module, state, comments\n                           FROM tmp_ir_translation_import\n                           WHERE type = 'model'\n                           ON CONFLICT (type, lang, name, res_id) WHERE type = 'model'\n                            DO UPDATE SET (name, lang, res_id, src, type, value, module, state, comments) = (EXCLUDED.name, EXCLUDED.lang, EXCLUDED.res_id, EXCLUDED.src, EXCLUDED.type, EXCLUDED.value, EXCLUDED.module, EXCLUDED.state, EXCLUDED.comments);\n                       "
odoo12c | ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
odoo12c | HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
odoo12c |  
odoo12c | 2018-10-20 14:14:40,708 1 ERROR odoo12_test_us odoo.http: Exception during JSON request handling. 
odoo12c | Traceback (most recent call last):
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 653, in _handle_exception
odoo12c |     return super(JsonRequest, self)._handle_exception(exception)
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
odoo12c |     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
odoo12c |     raise value
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 695, in dispatch
odoo12c |     result = self._call_function(**self.params)
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
odoo12c |     return checked_call(self.db, *args, **kwargs)
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
odoo12c |     return f(dbname, *args, **kwargs)
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
odoo12c |     result = self.endpoint(*a, **kw)
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 938, in __call__
odoo12c |     return self.method(*args, **kw)
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
odoo12c |     response = f(*args, **kw)
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
odoo12c |     action = self._call_kw(model, method, args, {})
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
odoo12c |     return call_kw(request.env[model], method, args, kwargs)
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
odoo12c |     return _call_kw_multi(method, model, args, kwargs)
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
odoo12c |     result = method(recs, *args, **kwargs)
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/addons/base/wizard/base_language_install.py", line 36, in lang_install
odoo12c |     mods.with_context(overwrite=self.overwrite)._update_translations(self.lang)
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 860, in _update_translations
odoo12c |     self.env['ir.translation'].load_module_terms(mod_names, filter_lang)
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_translation.py", line 760, in load_module_terms
odoo12c |     tools.trans_load(self._cr, trans_file, lang, verbose=False, module_name=module_name, context=context)
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/tools/translate.py", line 1015, in trans_load
odoo12c |     result = trans_load_data(cr, fileobj, fileformat, lang, verbose=verbose, module_name=module_name, context=context)
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/tools/translate.py", line 1155, in trans_load_data
odoo12c |     irt_cursor.finish()
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_translation.py", line 151, in finish
odoo12c |     """ % (self._model_table, self._table))
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
odoo12c |     return f(self, *args, **kwargs)
odoo12c |   File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
odoo12c |     res = self._obj.execute(query, params)
odoo12c | psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
odoo12c | HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
```

**Comment by my1649** [comment] 2018-11-08 02:56
The default 12 is now the image of enterprise. You may need to deploy a community by yourself.
close issue

**Comment by my1649** [comment] 2018-11-08 02:57
I wonder how you can run it well by the way.
https://github.com/odoo/docker/issues/222

**Comment by d-fence** [comment] 2020-01-22 10:09
I cannot reproduce.
I close it as there is no more activity on this issue.

**Closed by d-fence** 2020-01-22 10:09 UTC
