### ISSUE TITLE
[9.0] Exception during JSON request handling

### ISSUE THREAD

**Issue by medined** [odoo/docker#58] opened 2016-06-04 22:18 UTC
While I do see this error message, the web application seems to react normally to web requests.

I am using the following two lines to start ODOO:

{noformat}
docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name db postgres
docker run -p 8069:8069 --name odoo --link db:db -t odoo
{noformat}

After a few seconds, I see the message about JSON handling:

{noformat}
$ docker run -p 8069:8069 --name odoo --link db:db -t odoo
2016-06-04 22:15:11,759 1 INFO ? openerp: OpenERP version 9.0c-20160428
2016-06-04 22:15:11,759 1 INFO ? openerp: addons paths: ['/var/lib/odoo/addons/9.0', u'/mnt/extra-addons', u'/usr/lib/python2.7/dist-packages/openerp/addons']
2016-06-04 22:15:11,760 1 INFO ? openerp: database: odoo@172.17.0.2:5432
2016-06-04 22:15:12,004 1 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2016-06-04 22:15:14,523 1 INFO ? openerp.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2016-06-04 22:15:15,074 1 INFO ? openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2016-06-04 22:15:15,367 1 INFO ? openerp.http: HTTP Configuring static files
2016-06-04 22:15:15,373 1 INFO ? openerp.http: Generating nondb routing
2016-06-04 22:15:15,387 1 ERROR ? openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1624, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found
{noformat}

**Comment by sle-odoo** [comment] 2016-10-25 18:46
Closing as i cannot reproduce, also it looks like an upstream bug. You should probably re-open a ticket [here](https://github.com/odoo/odoo/issues) if you're still facing the issue.

Regards

**Closed by sle-odoo** 2016-10-25 18:46 UTC
