### ISSUE TITLE
Odoo Server Error - Unable to connect to SMTP Server

### ISSUE THREAD

**Issue by demogorgonz** [odoo/docker#153] opened 2017-12-30 17:11 UTC
Hello,

Bellow is odoo.conf : 

```
[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
; admin_passwd = admin
; csv_internal_sep = ,
; db_maxconn = 64
; db_name = False
; db_template = template1
; dbfilter = .*
debug_mode = True
; email_from = True
; limit_memory_hard = 2684354560
; limit_memory_soft = 2147483648
; limit_request = 8192
; limit_time_cpu = 60
; limit_time_real = 120
; list_db = True
; log_db = False
; log_handler = [':INFO']
; log_level = info
; logfile = None
; longpolling_port = 8072
; max_cron_threads = 2
; osv_memory_age_limit = 1.0
; osv_memory_count_limit = False
; smtp_password = False
smtp_port = 25
smtp_server = 172.17.0.1
; smtp_ssl = False
; smtp_user = False
; workers = 0
; xmlrpc = True
; xmlrpc_interface = 
; xmlrpc_port = 8069
; xmlrpcs = True
; xmlrpcs_interface = 
; xmlrpcs_port = 8071
```

**Server: Docker host
Image: https://hub.docker.com/_/odoo/**

smtp_server is docker host (172.17.0.1), sendmail is configured to listen on all interfaces and connectivity and email sending is tested from different docker container.

Debug mode is enabled however there is no log or connectivity try to the MTA.
Sendmail logs are empty regarding odoo instance.

Is this a bug ? Have anyone tested mail functionality on docker image?

**Comment by smellems** [comment] 2018-05-18 17:45
I'm also running odoo 11 in docker and having problems getting outgoing email to work.  I get the following error trying to send an email in odoo
`[Errno 110] Connection timed out`

I had the configuration in the odoo.conf file and also tried configuring it in the admin interface.  When clicking "test connection" it just spins and eventually returns with no feedback and no email.

Is there any way I can get more information as to what to problem is?  I can't find the log when Debug mode is enabled.

**Comment by spinus** [comment] 2018-10-09 04:28
I was debugging it a bit. With /usr/bin/python3 you can start testing connection using 'socket' module.
I can only connect to network resources on 80 and 443 ports. I cannot connect to any outgoing 22 or 143 or other ports.

**Comment by d-fence** [comment] 2018-10-10 12:14
Sorry for the late answer.
I cannot reproduce, I tested an Odoo 11 standard docker image with an smtp mail catcher on localhost 172.18.0.1 and mails are working.
I'm closing this one as it's probably a docker configuration problem.

**Closed by d-fence** 2018-10-10 12:14 UTC
