### ISSUE TITLE
error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by aidoskz** [odoo/docker#226] opened 2018-11-09 20:03 UTC
https://github.com/odoo/docker/blob/3b5c6ae6aa21ea4d590a5d305fc9b0f4a447e218/11.0/Dockerfile#L39

Building wheels for collected packages: num2words
  Running setup.py bdist_wheel for num2words: started
  Running setup.py bdist_wheel for num2words: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hicmf18p/num2words/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp_hmcvi9ipip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

###   error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for num2words
  Running setup.py clean for num2words
Failed to build num2words

**Comment by ecrazor1911** [comment] 2018-11-29 17:07
Try this:

```Dockerfile
RUN pip3 install wheel 
RUN pip3 install num2words xlwt 
```

or

```Dockerfile
RUN pip3 install wheel && pip3 install num2words xlwt 
```

**Comment by d-fence** [comment] 2020-01-22 08:35
I cannot reproduce.
I close this issue as it's an old one. Re-open if needed.
Thanks.

**Closed by d-fence** 2020-01-22 08:35 UTC
